### PR TITLE
Robson Fagundes - MongoDB - Exercicio 03 Resolvido

### PR DESCRIPTION
**Pull request by robsonfagundes**
$lt, $lte
$gt, $gte
$and, $or, $nor

### CODE REVIEW

**Comment by robsonfagundes** [comment]
@suissa for what reason?

**Comment by asfelix** [comment]
@robsonfagundes o @suissa criou outro repositório especialmente para os exercícios do curso: https://github.com/Webschool-io/be-mean-instagram-mongodb-excercises

**Comment by robsonfagundes** [comment]
@asfelix Aham... https://github.com/robsonfagundes/be-mean-instagram/tree/master/apostila/classes/mongodb/exercises

**Comment by robsonfagundes** [comment]
vlw @asfelix !!! agora que abri o  face vi!!!

**Pull request closed without merging**
